services:
  postgres:
    image: 'postgres:latest'
    environment:
#      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: password # change / remove for actual implementation
      # TODO change from hunter to postgres
      POSTGRES_USER: hunter
      PGDATA: /data/postgres

    ports:
      - '5432:5432'
    volumes:
      - db:/data/postgres
volumes:
  db:
