services:
  postgres:
    image: 'postgres:latest'
    environment:
#      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: password
      POSTGRES_USER: hunter
      PGDATA: /data/postgres
    ports:
      - '5432'
    volumes:
      - db:/data/postgres
volumes:
  db:
