JWT_SECRET: "7171cc2490e9ec21ee90c0500c2ca64ee42da419e1605386ac3cec3de55f7690"
JWT_EXPIRATION: 7200000 
ALLOWED_ORIGINS: "*"


spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/hunter"
    username: "hunter"
    password: "password"